### ISSUE TITLE
Authorization for client to proxy?

### ISSUE THREAD

**Issue by DonMartin76** [RobustPerception/PushProx#17]
Are there mechanisms in the `client` to add some kind of authorization headers for accessing the proxy already? E.g., BasicAuth or some custom header containing an API key or similar? The documentation on authentication/authorization is a little vague there.

**Use case:**

* Run PushProx e.g. inside a Kubernetes cluster, so that Prometheus can access it directly via Kubernetes FQDN (`http://pushprox.default.svc.cluster.local:8080` or similar)
* Expose PushProx via APIm (Kong/glorified nginx) to the outside, so that you get routed to PushProx if you have the right set of credentials
* Pass on authorization parameters to the `client` call outside the cluster, so that it can access the proxy instance via the nginx --> This is where the authorization is required, e.g. a custom header (`X-ApiKey`) or some other type of credential, possibly OAuth2 Client Credentials flow.

Picking up the ball from my issue on pushgateway pointing to https://github.com/Haufe-Lexware/pushgateway-pruner ...

Would this work in principle, or did I once more think in the wrong direction?

I was thinking of something like

`client --proxy-url=<...> --username=someuser --password=somepassword`

or

`client --proxy-url=<...> --custom-header=X-ApiKey=somesecretapikey`

**Comment by DonMartin76** [comment]
OK, found https://github.com/RobustPerception/PushProx/issues/12 wrt basic auth.

**Comment by brian-brazil** [comment]
Yes, you can put PushProxy behind a reverse proxy that provides basic auth.
