### ISSUE TITLE
Client throws runtime error

### ISSUE THREAD

**Issue by yoshz** [RobustPerception/PushProx#18]
Tried to make it work but on every scrape the client results in a runtime error:

```
feb 28 21:19:13 zbook pushprox-client[23421]: panic: runtime error: invalid memory address or nil pointer dereference
feb 28 21:19:13 zbook pushprox-client[23421]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x6c85ef]
feb 28 21:19:13 zbook pushprox-client[23421]: goroutine 1 [running]:
feb 28 21:19:13 zbook pushprox-client[23421]: main.loop(0x8f3ce0, 0xc420075ce0)
feb 28 21:19:13 zbook pushprox-client[23421]:         /home/yosh/go/src/github.com/robustperception/pushprox/client/client.go:127 +0xaef
feb 28 21:19:13 zbook pushprox-client[23421]: main.main()
feb 28 21:19:13 zbook pushprox-client[23421]:         /home/yosh/go/src/github.com/robustperception/pushprox/client/client.go:147 +0x381
```

Also get a runtime error when the proxy is not reachable.

**Comment by brian-brazil** [comment]
There was an error that wasn't being handled. I've pushed a fix, can you try again?

**Comment by yoshz** [comment]
Now have a better error message
```
level=error ts=2018-03-01T17:10:39.575055939Z caller=client.go:128 msg="Error reading request:" err="malformed HTTP request \"<html>\""
```
Not sure what I am doing wrong though. The proxy runs inside a Kubernetes cluster and gets scraped from the Prometheus. The client is connect with the proxy, but ends up with a wrong response body.

**Comment by brian-brazil** [comment]
Sounds like it might be hitting the wrong page. Does tcpdump indicate what it's picking up?

**Comment by yoshz** [comment]
Problem resides in that there was a reverse proxy in between which timed out. The client was receiving a 503 message which explains the error.
Exposing the proxy now on a different port which solves my problem.
Thanks for your help.
