### ISSUE TITLE
Log level of response to /clients

### ISSUE THREAD

**Issue by toerb** [RobustPerception/PushProx#19]
Hi!

ATM every response for a request to /clients on the proxy generate an error log entry.
I think the log level in this line should be changed from Error to Info.
https://github.com/RobustPerception/PushProx/blob/46f8f2fcf85f5b502b06e3f43e078f44c9d6b943/proxy/proxy.go#L97

**Comment by brian-brazil** [comment]
That makes sense, would you like to send a PR?

**Comment by toerb** [comment]
With the merged change the line is no longer logged with Error level.
