### ISSUE TITLE
prometheus config

### ISSUE THREAD

**Issue by wuyongxiu** [RobustPerception/PushProx#3]
![image](https://user-images.githubusercontent.com/17407521/30269585-e342a5c0-971b-11e7-85df-b545c89ee250.png)

is it okay that the FQDN of client is written into ip+port?  for example, localhost:9100，192.168.x.x:9100 and so on...

**Comment by wuyongxiu** [comment]
I have configed client,proxy,prometheus following the instruction, but I am stucking into this mistake below.  I don't know why.
https://github.com/RobustPerception/PushProx

**Comment by brian-brazil** [comment]
Yes, the IP should also work presuming that's what you've passed as the `-fqdn` flag to the client.

**Comment by wuyongxiu** [comment]
Yep, I add the flag, and it works in go1.9.  But if the version is under 1.9 such as go1.8, the two flags would not work.

**Comment by wuyongxiu** [comment]
![image](https://user-images.githubusercontent.com/17407521/30303617-e1a7c328-979b-11e7-8431-e7bc0f593881.png)
and it's not worked when I set -proxy.url=http://localhost:8080/ , while -proxy.url=http://localhost:8080 is okay.

**Comment by brian-brazil** [comment]
Sounds like it's working then.
