### ISSUE TITLE
Scalability concerns

### ISSUE THREAD

**Issue by Silex** [RobustPerception/PushProx#39]
Hello,

Sorry if I missunderstand the code (new to go), but based on https://github.com/RobustPerception/PushProx/blob/master/client/client.go#L163 and https://github.com/RobustPerception/PushProx/blob/master/client/client.go#L235 am I right to understand that the client can only do one scrape per second?

So for example if you want to avoid NAT and have 10 equipements you want to monitor every 5 seconds, PushProx will not "work" right? I guess the simple solution is to run several clients (e.g 1 per equipment).

**Comment by brian-brazil** [comment]
That code path is only if there's a failure, in normal operation you should be able to handle that.

**Comment by Silex** [comment]
Right... wait, so that means the client is *constantly* doing HTTP posts to the proxy?
