### ISSUE TITLE
How to change the log level?

### ISSUE THREAD

**Issue by chaudum** [RobustPerception/PushProx#4]
Is there a way to set the log level of pushprox?
At default it logs at level INFO, which is quite a log and spams the log directory :(

Would be nice to support the `-log.level` flag, like alot of other go programs do.

**Comment by brian-brazil** [comment]
It does have a `-log.level` flag.

**Comment by chaudum** [comment]
@brian-brazil I get the following error when providing the flag
```
[admin@monitoring ~]$ /usr/bin/pushprox -log.level=warn
flag provided but not defined: -log.level
Usage of /usr/bin/pushprox:
  -registration.timeout duration
    	After how long a registration expires. (default 5m0s)
  -scrape.default-timeout duration
    	If a scrape lacks a timeout, use this value. (default 15s)
  -scrape.max-timeout duration
    	Any scrape with a timeout higher than this will have to clamped to this. (default 5m0s)
  -web.listen-address string
    	Address to listen on for proxy and client requests. (default ":8080")
```

**Comment by chaudum** [comment]
I actually have a systemd service file where I read /etc/defaults/pushprox as environment file and pass it to the binary

**Comment by brian-brazil** [comment]
That should be fixed now, note that there's now two hyphens in flag names.
