### ISSUE TITLE
Poll frequency?

### ISSUE THREAD

**Issue by saulp** [RobustPerception/PushProx#52]
I couldn't find in the documentation just how often the client polls the proxy.

I presume the answer is once per second, as per the below line in **client.go**?

`			time.Sleep(time.Second) // Don't pound the server. TODO: Randomised exponential backoff.
`

Thanks!

**Comment by brian-brazil** [comment]
That code is only used in case of error. It'll generally always have one poll going, though attempting sub-second scrape intervals is generally unwise before even adding PushProx to the mix.

**Comment by saulp** [comment]
Thanks for the prompt reply, Brian. I was actually looking to *reduce* the
frequency from (what I thought was) 1 second, to something like 5 or 10
seconds.

**Comment by saulp** [comment]
Brian, after looking into this further, I think my question stemmed from a lack of understanding of the model...

I originally thought that, every so often and under a set frequency, the _client_ would initiate a connection: send to the proxy a request like "hey is there an outstanding request for my metrics?", that the proxy would then respond with either "not at the moment" or "yup send me your stuff", and if the latter then the client would send the metrics - and that was it for that connection.

But after I spent some time looking at tcpdump output, I see that is not exactly the case... Looks like there is only one connection going all the time, and sometimes (every minute) the client will send a packet first (I think 'keepalives', but not sure since I'm using an HTTPS reverse proxy so the contents are encrypted), and other times (also every minute) it will be the proxy initiating with a scrape request. 

Although, the above is true with a 1-minute scrape frequency... If I set a longer interval (say 2 min), then I see an error every other minute:

Client-side:
`level=error ts=2019-06-04T14:22:28.153Z caller=client.go:167 msg="Error reading request:" err="invalid method \"<!DOCTYPE\""`

Proxy-side:
`level=info ts=2019-06-04T14:22:29.178Z caller=proxy.go:125 msg="Error WaitForScrapeInstruction:" err="request is expired"`

I don't see the above messages when the scrape frequency is 1-minute... I'd love to hear your thoughts Brian?

**Comment by saulp** [comment]
@brian-brazil , I'll close this issue as my original question has been answered. Thanks for your reply.

As for the "invalid method" errors, while I'm still seeing those (and suspect them to be at the root of a gaps issue I am having), I'll first try installing the latest versions of both pushprox client and server, and should that not help I'll log that as its own separate issue.

Thanks again,
Saul
