### ISSUE TITLE
TLS between server and client

### ISSUE THREAD

**Issue by glaslos** [RobustPerception/PushProx#59]
Hi, would like to have TLS encryption between the prox client and prox proxy. The recommendations so far has been using a reverse proxy. I'm wondering how this is possible with the proxy overwriting host when sending the response which breaks the routing in the reverse proxy. I assume I'm missing something so I'd appreciate if someone with experience setting this up nudging me into the right direction.

**Comment by brian-brazil** [comment]
It should just work.

**Comment by glaslos** [comment]
My bad. I was using `localhost` as the target which works surprisingly well until you introduce a proxy ;)
