### ISSUE TITLE
Incorrect fqdn check?

### ISSUE THREAD

**Issue by pramodc** [RobustPerception/PushProx#64]
The check below in the client code at line https://github.com/RobustPerception/PushProx/blob/master/client/client.go#L112 seems incorrect, please confirm.

```
	if request.URL.Hostname() != fqdnURL.Hostname() {
		c.handleErr(request, client, errors.New("scrape target doesn't match client fqdn"))
		return
	}
```

If fqdn provided to the client is "xyz" and the request url is "xyz:8000", the fqdnURL.HostName() will be empty ("") while the request.URL.Hostname() will be "xyz".

**Comment by LiGeNvidia** [comment]
I think this is bug.

**Comment by troyanov** [comment]
It is a bug, because FQDN doesn't contain any schema.
I've created a PR https://github.com/RobustPerception/PushProx/pull/65 that should fix that.
