### ISSUE TITLE
Cannot build docker image

### ISSUE THREAD

**Issue by msamendinger** [RobustPerception/PushProx#73]
In the [Dockerfile](https://github.com/RobustPerception/PushProx/blob/master/Dockerfile) the `go get` command pulls *github.com/robustperception/pushprox/proxy* and *github.com/robustperception/pushprox/client*
```
RUN go get github.com/robustperception/pushprox/proxy
WORKDIR $GOPATH/src/github.com/robustperception/pushprox/proxy
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build

RUN go get github.com/robustperception/pushprox/client
WORKDIR $GOPATH/src/github.com/robustperception/pushprox/client
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build
```
It seems like the directories got moved in `github.com/robustperception/pushprox/cmd/{proxy,client}`
To get the `docker build` working I had to change the path in line 6,7,10,11,21 and 22.

Was this the right way to go or did I overlook something?

Two other things I stumbled upon
* in your circleci builds you updated to golang:1.13 while in the dockerfile still golang:1.12 is used. 
* in the build stage $GOPATH is used but when the binaries get copied /go is hardcoded. As no GOPATH default is set in the Dockerfile this could break when `golang`s GOPATH changes

**Comment by SuperQ** [comment]
It looks like the Dockerfile needs to be updated for the new build layout.

**Comment by msamendinger** [comment]
Thanks, for the updated Dockerfile.
Theres another question I have about the comment `# Requires `promu crossbuild` artifacts.` I understand that I have to do something to get the binaries cross compiled in order to copy them to the docker container.

Can you push me into the right direction on what I have to do to cross compile it? 

Thanks

**Comment by SuperQ** [comment]
It's literally just `promu crossbuild`. You can setup promu with `make promu`.

**Comment by msamendinger** [comment]
That helped :) Didn't have my $GOPATH/bin in $PATH so I couldn't run `promu crossbuild` at first but looks good now.
